// @ts-check
// Feed Chart copy, English and Spanish, by key. Product and recipe names stay English.
// tests/feedchart.test.ts fails when a key is missing from either language or when
// the app asks for a key that does not exist.

/** @type {Record<string, string>} */
const en = {
  // Page chrome
  "tool.name": "Feed Chart",
  "title.3part": "3-Part Feed Chart",
  "title.cplus": "Component Plus Feed Chart",
  "title.team.3part": "Feed Chart · Team",
  "title.team.cplus": "Component Plus Feed Chart · Team",
  "lede.stock": "Stock tank recipes and injection rates for every phase.",
  "lede.direct": "Product per volume of reservoir for every phase.",
  "team.banner": "Internal team copy: custom stock strength and tank size. Do not share this link with customers.",
  "theme.toggle": "Switch light or dark mode",
  "lang.toggle": "Español",
  "lang.toggleLabel": "Ver en español",
  "foot.back": "All calculator tools",
  "foot.contact": "Using an earlier chart? Contact us at order@solsticeag.com or +1 844-420-6883.",

  // Actions
  "action.edit": "Edit",
  "action.exportPdf": "Export PDF",
  "action.share": "Share link",
  "action.copy": "Copy summary",
  "action.done": "Show chart",
  "action.close": "Close",
  "toast.copied": "Summary copied",
  "toast.linkCopied": "Link copied",
  "toast.failed": "Couldn't copy. Select the address bar and copy it.",

  // Setup chips
  "chip.stock": "Stock concentrate",
  "chip.direct": "Direct to reservoir",
  "chip.dosers3": "3 dosers",
  "chip.dosers2": "2 dosers",
  "chip.tankGal": "{vol} gal tanks",
  "chip.custom": "Custom {a} / {b} / {bl} lb/gal",
  "chip.caStock": "CaNO3 {rate} lb/gal",
  "chip.nearRipen": "Near Ripen finish",
  "chip.high": "High strength EC",
  "chip.standard": "Standard EC",
  "chip.customEc": "Custom EC",
  "chip.schedule.commercial": "Commercial schedule",
  "chip.schedule.swell-flower": "Swell through flower",
  "chip.schedule.custom": "Custom recipes",
  "chip.schedule.locked": "Swell locked",
  "chip.phz": "PhosZyme",

  // Units
  "unit.mL/gal": "mL/gal",
  "unit.injection %": "injection %",
  "unit.ratio": "ratio",
  "unit.mL/L": "mL/L",
  "unit.g/gal": "g/gal",
  "unit.g/L": "g/L",
  "unitCaption.mL/gal": "mL of stock per gallon of feed water",
  "unitCaption.injection %": "injection rate, % of flow",
  "unitCaption.ratio": "injector ratio, stock to water",
  "unitCaption.mL/L": "mL of stock per liter of feed water",
  "unitCaption.g/gal": "grams of product per gallon of reservoir",
  "unitCaption.g/L": "grams of product per liter of reservoir",

  // Phases and chart
  "phase.short.0": "Veg / Moms",
  "phase.short.1": "Wk 1–2",
  "phase.short.2": "Wk 3–5",
  "phase.short.3": "Wk 6–8/9",
  "phase.short.4": "Final 1–2 Wks",
  "phase.long.0": "Veg / Moms",
  "phase.long.1": "Week 1–2",
  "phase.long.2": "Week 3–5",
  "phase.long.3": "Week 6–8/9",
  "phase.long.4": "Final 1–2 Wks",
  "sec.schedule": "Feed schedule",
  "chart.phase": "Phase",
  "chart.ec": "EC",
  "chart.recipe": "Recipe",
  "chart.targetEc": "Target EC",
  "chart.dripperPh": "Dripper pH",
  "chart.ph": "pH {range}",
  "chart.notServed": "Not served",
  "chart.bars": "Bars show each part's share of EC.",
  "chart.subEc": "Small figures are each part's EC contribution.",
  "chart.valuesAre": "Values are {caption}.",
  "chart.disclaimer": "These feed charts are not a prescription, but an example of the general ranges and relationship of EC and recipes that can be used. Each facility and cultivation methodology will require customization of EC values. See \"EC Considerations.\"",
  "ph.title": "Dripper pH",
  "ph.body": "Each phase's range follows its recipe and target EC, from the calcium-phosphate model. Raise pH with pH Up only up to the top of the range.",
  "ph.warm": "Lines running above {c} °C ({f} °F) should run the low end of the range.",
  "twoDoser.veg": "Veg / Moms is not served in 2-doser: a combined {combo} tank can't deliver a zero-{bloom} Veg recipe. Run veg / moms on a separate {a} + {b} feed.",
  "twoDoser.rates": "The two tanks run at different injection rates. Set each doser to the rate on its own row, then confirm with EC/PPM validation.",
  "twoDoser.equal": "At 0.75 lb/gal CaNO3 with a Swell finish, both dosers run the same rate.",
  "custom.mkpCool": "MKP above 1.33 lb/gal may not fully dissolve in cool water. Mix in room-temperature water and confirm the validation EC before use.",

  // Stock tanks
  "sec.tanks": "Stock tanks",
  "tanks.each": "{vol} {unit} each",
  "tanks.split": "Tank 1 {a} {unit} · Tank 2 {b} {unit}",
  "tank.n": "Tank {n}",
  "tank.validates": "Validates at {ec} EC",
  "tank.validatesTotal": "Tank validates at {ec} EC",
  "tank.phzAdds": "PhosZyme adds {ec} EC to this tank's reading.",
  "tank.with": "with {items}",
  "tank.validation": "Validate each tank: {ml} mL of stock in {water} of RO water should read its validation EC.",
  "water.us": "5 gal",
  "water.metric": "20 L",

  // Mixing
  "sec.mix": "Mixing steps",
  "sec.notes.stock": "Stock concentrate notes",
  "sec.notes.direct": "Direct to reservoir notes",
  "step.stock.1": "Start with clean stock tanks marked at target volume.",
  "step.stock.2": "Add RO water to 50% of target volume; begin agitating tank.",
  "step.stock.3": "Add fertilizer over 5 minutes, while continuing to agitate tank.",
  "step.stock.4": "Add RO water to target volume; mix for 10 more minutes.",
  "step.stock.5": "Validate and adjust stock tank as necessary (see Validation).",
  "step.two.1": "Start with two clean stock tanks marked at target volume.",
  "step.two.2": "Add RO water to 50% of target volume in each tank; begin agitating.",
  "step.two.3part.3": "Tank 1: Add Part A over 5 minutes while agitating. Tank 2: Add Part B, then PhosZyme, then Bloom over 5 minutes while agitating. Bloom is the largest addition and dissolves slowest.",
  "step.two.3part.3.nophz": "Tank 1: Add Part A over 5 minutes while agitating. Tank 2: Add Part B, then Bloom over 5 minutes while agitating. Bloom is the largest addition and dissolves slowest.",
  "step.two.cplus.3": "Tank 1: Add calcium nitrate over 5 minutes while agitating. Tank 2: Add Component Plus and let it dissolve fully, then PhosZyme, then MKP, while agitating (MKP dissolves slowly in cold water).",
  "step.two.cplus.3.nophz": "Tank 1: Add calcium nitrate over 5 minutes while agitating. Tank 2: Add Component Plus and let it dissolve fully, then MKP, while agitating (MKP dissolves slowly in cold water).",
  "step.two.4": "Add RO water to target volume in each tank; mix for 10 more minutes.",
  "step.two.5": "Validate and adjust each stock tank as necessary (see Validation).",
  "step.two.6": "Set each doser to its own injection rate from the chart; confirm final solution EC/PPM.",
  "step.dtr.1": "Fill reservoir to 90% of intended final volume; begin agitation.",
  "step.dtr.2": "If using pH Down: add pH Down to target range before adding fertilizer.",
  "step.dtr.add": "Add {product}; agitate 3–5 minutes.",
  "step.dtr.addPhz": "Add {product} and PhosZyme; agitate 3–5 minutes.",
  "step.dtr.6": "Check EC/PPM, then slowly top off with water until your target EC/PPM is reached.",
  "step.dtr.7": "If using pH Up: add pH Up to target range after EC/PPM is on target.",
  "step.dtr.8": "Validate pH/EC and adjust as necessary.",
  "note.stock.3part.1": "Mix each part into its own stock tank; validate stock EC before use and adjust as necessary.",
  "note.stock.3part.2": "Tank 1 holds Part A alone. Tank 2 holds Part B and Bloom together: mix Part B first, then Bloom. Validate each stock tank's EC before use and adjust as necessary.",
  "note.ro": "All feed charts are based on using RO water. If your starting water has any EC, account for that in the total EC.",
  "note.phz.3part": "If using PhosZyme, mix it into the Part B stock tank, never with Part A.",
  "note.phz.3part.two": "If using PhosZyme, mix it into Tank 2 after Part B and before Bloom, never with Part A.",
  "note.oxidizers.stock": "Avoid mixing strong oxidizers, especially peroxides, into stock tanks.",
  "note.injectors": "Set injectors to the listed rates, then confirm final solution EC/PPM at the emitter.",
  "note.injectors.two": "The two tanks run at different injection rates. Set each doser to the rate on its own row, then confirm final solution EC/PPM at the emitter.",
  "note.cplus.shelf": "Use C+ stock concentrates within 14 days of mixing. Store in opaque containers at room temperature, off the ground, and away from direct or artificial light.",
  "note.cplus.separate": "Keep CaNO3, Component Plus, and MKP in separate stock tanks.",
  "note.cplus.separate.two": "Keep CaNO3 alone in Tank 1. In Tank 2, dissolve Component Plus fully before adding MKP.",
  "note.cplus.validate": "Prepare stocks with RO water and validate each tank before use.",
  "note.phz.cplus": "Add PhosZyme to the Component Plus tank, never to the CaNO3 tank.",
  "note.phz.cplus.two": "Add PhosZyme after Component Plus and before MKP in Tank 2, never to the CaNO3 tank.",
  "note.dtr.days": "Reservoirs should be used within 5–7 days.",
  "note.dtr.oxidizers.us": "Avoid mixing strong oxidizers, especially peroxides, into reservoirs. If running a sterile reservoir, use calcium hypochlorite at about {g} g per 100 gal for {ppm} ppm.",
  "note.dtr.oxidizers.metric": "Avoid mixing strong oxidizers, especially peroxides, into reservoirs. If running a sterile reservoir, use calcium hypochlorite at about {g} g per 100 gal ({gL} g per 100 L) for {ppm} ppm.",
  "note.dtr.phz.3part": "If using PhosZyme, add it with Part B.",
  "note.dtr.phz.cplus": "If using PhosZyme, add it with Component Plus, after CaNO3 and before MKP.",

  // Validation
  "sec.validation": "Validation",
  "val.1": "Draw {ml} mL of concentrate from the stock tank.",
  "val.2": "Mix the sample into {water} of RO water.",
  "val.3": "Measure EC and compare to the Valid. EC column.",
  "val.4": "If the reading is off, adjust the tank and re-validate before use.",
  "val.phz": "PhosZyme in the {carrier} tank raises that tank's validation EC.",
  "stock.title": "{label} stock concentrate rates",
  "stock.tank": "Tank",
  "stock.part": "Part",
  "stock.validEc": "Valid. EC",
  "stock.tank2Total": "Tank 2 total",

  // Supplements
  "sec.supps": "Supplements",
  "supps.hint": "Add pH Up, BioFlo, or Triologic to this list in Edit.",
  "supp.si.name": "Front Row Si",
  "supp.si.rate": "{rate}",
  "supp.si.note": "Foliar spray, once weekly, from Veg through week 3 of flower.",
  "supp.phup.name": "Front Row pH Up",
  "supp.phup.rate": "{max} {unit} max",
  "supp.phup.note": "Raise pH into the chart's dripper range. Add last, in {inc} {unit} steps; wait {wait} minutes before re-measuring. Stop at {stop} {unit} on high-strength flower.",
  "supp.bioflo.name": "BioFlo",
  "supp.bioflo.rate": "{heavy} heavy · {maint} maintenance",
  "supp.bioflo.note": "Line cleaner for biofilm. Heavy clean: soak {soak} hours. Maintenance every {weeks} weeks.",
  "supp.tri.name": "Triologic",
  "supp.tri.rate": "{weekly} weekly",
  "supp.tri.note": "Microbial inoculant that amplifies mycorrhizal colonization. Weekly hand drench; up to {max} (for example at transplant).",
  "supp.additive": "Additive",
  "supp.rate": "Rate",
  "supp.notes": "Notes",
  "supp.title": "Additive usage rates",

  // EC guidance
  "ec.considerations": "EC considerations",
  "ec.considerationsBody": "Given the variance in facility infrastructure, cultivation methods, and cultivars, it's impossible to give a specific EC prescription that applies to all scenarios. Most facilities feed at 2.0–3.0 EC with Front Row Ag, and our \"Standard\" and \"High Strength\" feed charts reflect effective feeding strategies in this range.",
  "ec.higherLower": "Higher EC vs lower EC",
  "ec.higher": "Higher EC",
  "ec.lower": "Lower EC",
  "hl.0.h": "Smaller pots", "hl.0.l": "Larger pots",
  "hl.1.h": "Frequent irrigation", "hl.1.l": "Infrequent irrigation",
  "hl.2.h": "Consistent runoff", "hl.2.l": "Less runoff",
  "hl.3.h": "Substrate monitoring", "hl.3.l": "No substrate monitoring",
  "hl.4.h": "Higher PPFD", "hl.4.l": "Lower PPFD",
  "hl.5.h": "Heavy feeding strains", "hl.5.l": "Lower feeding strains",
  "hl.6.h": "Higher CO2", "hl.6.l": "Lower CO2",
  "hl.7.h": "Tight environmental control", "hl.7.l": "Less environmental control",
  "ec.contribution": "EC contribution",
  "ec.perUnit": "EC per {unit}",

  // Print
  "print.kicker": "{line} · {application}",
  "print.feedChart": "Feed Chart",
  "print.mixing": "Mixing Instructions",
  "print.preparedFor": "Prepared for",
  "print.notes": "Notes",
  "print.page": "Page {n} of {total}",
  "print.artTitle.stock": "How to make stock concentrate",
  "print.artTitle.direct": "Mixing step by step",
  "print.artTitle.line": "How the two-doser line is set up",
  "print.tankKey": "What each tank holds",
  "print.phUpDoser": "Optional third doser: pH Up",
  "print.qr": "More feed chart information",
  "art.stock.1": "Fill to {pct}% with RO water; start agitating",
  "art.stock.2": "Add product over {min} min",
  "art.stock.3": "Top off; mix {min} more min",
  "art.stock.4": "Validate: {ml} mL in {water} RO",
  "art.dtr.1": "Fill to {pct}%; start agitating",
  "art.dtr.2": "Add each part; {min} min apart",
  "art.dtr.3": "Top off to target EC",
  "art.dtr.4": "pH Up last; check pH at the dripper",
  "lines.3part": "3-Part",
  "lines.cplus": "Component Plus",
  "summary.title": "Front Row Ag Feed Chart",
  "summary.facility": "Facility: {name}",
  "summary.link": "Chart link: {url}",

  // Edit sheet
  "edit.title": "Customize your feed chart",
  "field.facility": "Facility name",
  "field.facilityHelp": "Optional. Prints on the chart.",
  "field.facilityPlaceholder": "Facility name",
  "field.application": "Application",
  "opt.stock": "Stock concentrate",
  "opt.direct": "Direct to reservoir",
  "help.more": "What do these mean?",
  "help.application.stock": "Stock concentrate is the standard commercial setup. Fertilizer is pre-mixed into concentrated stock tanks, then injected into the irrigation line by dosing equipment (injectors). The chart shows how much product goes in each stock tank and the injection rate for each doser.",
  "help.application.direct": "Direct to reservoir is for facilities that mix nutrients directly into a reservoir or batch tank at working strength, with no stock tanks or injectors. The chart shows how much product to add per gallon (or per liter) of final solution.",
  "field.dosers": "Dosers",
  "opt.dosers3": "3 dosers",
  "opt.dosers2": "2 dosers",
  "help.dosers.3part.3": "3 dosers: Part A, Part B, and Bloom each get their own stock tank and injector. This is the standard setup and allows per-phase recipe changes.",
  "help.dosers.3part.2": "2 dosers: Part A in Tank 1, and Part B + Bloom combined in Tank 2. A combined tank fixes the Part B-to-Bloom ratio, so every flower phase runs the Swell recipe. Tank 1 is the same Part A tank as the 3-2-2 build. The two tanks run at different injection rates.",
  "help.dosers.cplus.3": "3 dosers: CaNO3, C+, and MKP each get their own injector, mixed at 1 lb per gallon (1-1-1). Injection rates differ between tanks since each product carries a different share of the total EC.",
  "help.dosers.cplus.2": "2 dosers: CaNO3 alone in Tank 1, and C+ + MKP combined in Tank 2 at 0.75 + 1.00 lb/gal. Calcium can never share a tank with phosphate or sulfate, so CaNO3 always stays alone. The combined tank fixes the C+-to-MKP ratio, so flower runs Swell with an optional Near Ripen final phase.",
  "field.method": "Mixing method",
  "opt.custom": "Custom",
  "help.method.3-2-2": "3-2-2 is the standard method. Three 25 lb bags of Part A go into a 50 gal stock tank (75 lb at 1.5 lb/gal). Part B and Bloom each get two 25 lb bags in 50 gal (50 lb at 1 lb/gal). Injection rates come out equal across all three parts on the Stack recipe, and equal for Part A and Part B on Veg; other recipes run each part at its own rate.",
  "help.method.1-1-1": "1-1-1 mixes everything at 1 lb per gallon: 50 lb of each part in 50 gal stock tanks. It is a lower concentration than 3-2-2. Injection rates differ between parts since each contributes a different share of the total EC.",
  "help.method.4-3-3": "4-3-3 mixes Part A at 1.87 lb/gal in 53.5 gal, and Part B and Bloom at 1.25 lb/gal in 60 gal.",
  "help.method.custom": "Custom sets the pounds charged in each tank and the tank size. Rates and validation ECs recalculate from these entries.",
  "help.method.cplus": "Component Plus stock mixes at 1 lb per gallon in each of the three tanks (1-1-1). Injection rates differ between tanks, since each product carries a different share of the total EC.",
  "field.tankSize": "Stock tank size",
  "field.tankUnit": "gal per stock tank",
  "help.tank.3part": "Applied to both stock tanks. The 50 gal default fits a standard 55 gal barrel. Tank 2 is the more dilute tank and runs at a higher injection rate, so it empties roughly 1.7 times faster than Tank 1; size up or plan refills.",
  "help.tank.cplus": "Applied to each stock tank. Choose a volume you will use within 14 days.",
  "help.tank.custom": "Applied to all three tanks.",
  "help.tank.min": "Minimum {min} gal.",
  "field.customLbs": "Fertilizer per tank",
  "field.lbCharged": "lb charged",
  "help.customLbs": "Internal only. lb/gal, injection rates, and validation ECs recalculate from these entries. Capped at {a} / {b} / {bl} lb/gal ({names}). Validate stock EC before use.",
  "field.caStock": "CaNO3 stock concentration",
  "opt.ca.0.75": "0.75 lb/gal · equal-rate Swell",
  "opt.ca.1": "1.00 lb/gal · whole bag",
  "help.caStock": "Tank 2 stays at 0.75 lb/gal Component Plus + 1.00 lb/gal MKP. The 1.00 lb/gal CaNO3 option needs separate injector rates.",
  "field.finalPhase": "Final phase",
  "opt.fp.swell": "Swell",
  "opt.fp.near-ripen": "Near Ripen",
  "help.finalPhase": "Near Ripen holds calcium at the Ripen share (31.5% of total EC) and gives the remaining 68.5% to the fixed C+ + MKP tank. It is a two-tank approximation, not the three-product Ripen recipe.",
  "field.units": "Output units",
  "field.ec": "Target EC",
  "opt.high": "High strength",
  "opt.standard": "Standard",
  "help.ec": "Editing any phase's EC switches to Custom.",
  "field.schedule": "Recipe schedule",
  "opt.schedule.commercial": "Commercial",
  "opt.schedule.swell-flower": "Swell through flower",
  "opt.schedule.custom": "Custom",
  "help.schedule.commercial": "Commercial (Stack → Swell), the default chart, is the simplified production program: Veg / Moms on Veg, the Stack recipe through early flower (Wk 1–2), then Swell for the rest, finishing on Ripen. Swell steps down through mid-flower: weeks 3–5 at the higher Swell EC (2.7 High / 2.2 Standard), weeks 6–8/9 at the lower (2.4 High / 2.0 Standard).",
  "help.schedule.swell-flower": "Swell through flower keeps Veg / Moms on the Veg recipe, then runs Swell for the whole flower cycle, the simplest single-recipe flower program. As high-intensity LED, under-canopy lighting, and precision irrigation have raised average feed EC, Swell delivers better outcomes at those higher EC levels.",
  "help.schedule.custom": "Custom appears when you change a phase's recipe below.",
  "help.schedule.locked.3part": "2-doser mode locks every phase to the Swell recipe: the combined tank is weighed to Swell's Part B-to-Bloom ratio and can't be re-split per phase.",
  "help.schedule.locked.cplus": "2-doser mode runs the fixed C+ + MKP tank on Swell through flower. Final phase can hold Swell or taper calcium to Near Ripen.",
  "field.recipes": "Recipe per phase",
  "field.supps": "Supplements",
  "opt.phz": "PhosZyme",
  "opt.phup": "pH Up",
  "opt.bioflo": "BioFlo",
  "opt.tri": "Triologic",
  "help.supps": "PhosZyme changes the chart. pH Up, BioFlo, and Triologic add their rates to the Supplements list and summary; the printed chart lists every additive.",
  "help.phz.3part": "PhosZyme goes in its carrier stock tank at 10% of the carrier's weight (5 lb per 50 lb tank), which keeps the applied dose at or near 0.4 g/gal. The carrier is Part B (or the combined B + Bloom tank on 2 dosers). PhosZyme is not calcium-compatible, so it never goes in a tank with Part A. The chart scales every dose down slightly so total EC, including PhosZyme's, still hits your target.",
  "help.phz.cplus": "PhosZyme goes in the Component Plus tank at 10% of the C+ weight (5 lb per 50 lb tank), which keeps the applied dose at or near 0.4 g/gal. On 2 dosers the carrier is the combined C+ + MKP tank. PhosZyme is not calcium-compatible, so it never goes in a tank with CaNO3. The chart scales every dose down slightly so total EC, including PhosZyme's, still hits your target.",
  "help.phup": "pH Up raises pH into the dripper range shown on the chart for each phase. Add it last, after all nutrients, in {inc} {unit} steps, and wait {wait} minutes before re-measuring. Maximum {max} {unit} total; high-strength flower should stop at {stop} {unit}.",
  "help.bioflo": "BioFlo is a bioenzymatic line cleaner that removes biofilm from irrigation lines. It is not a feed additive; use it as a periodic soak between or during cycles.",
  "help.tri": "Triologic is a microbial inoculant containing Mycorrhization Helper Bacteria. It amplifies mycorrhizal colonization as a weekly hand-water drench alongside a separate mycorrhizal inoculant.",
  "help.si": "Front Row Si is a foliar spray; its rate is always listed with the supplements.",

  // Access gate (C+)
  "gate.title": "Front Row Ag · Component Plus Calculator",
  "gate.intro": "This calculator is part of Front Row Ag's commercial Component Plus program and is available to participating customers. Enter the access code provided by your Front Row Ag representative.",
  "gate.placeholder": "Access code",
  "gate.unlock": "Unlock Calculator",
  "gate.error": "That code didn't match. Check with your Front Row Ag representative.",
  "gate.team.title": "Front Row Ag · Team Feed Chart",
  "gate.team.intro": "Team mode is for the Front Row Ag team. Enter the team code from the Notion Team Tools page.",
  "gate.team.error": "That code didn't match. The team code is on the Notion Team Tools page.",
};

/** @type {Record<string, string>} */
const es = {
  "tool.name": "Tabla de alimentación",
  "title.3part": "Tabla de alimentación 3 Partes",
  "title.cplus": "Tabla de alimentación Component Plus",
  "title.team.3part": "Tabla de alimentación · Equipo",
  "title.team.cplus": "Tabla de alimentación Component Plus · Equipo",
  "lede.stock": "Recetas de tanques de concentrado y tasas de inyección para cada fase.",
  "lede.direct": "Producto por volumen en reserva para cada fase.",
  "team.banner": "Copia interna del equipo: concentración y tamaño de tanque personalizados. No comparta este enlace con clientes.",
  "theme.toggle": "Cambiar modo claro u oscuro",
  "lang.toggle": "English",
  "lang.toggleLabel": "View in English",
  "foot.back": "Todas las calculadoras",
  "foot.contact": "¿Usa una tabla anterior? Contáctenos en order@solsticeag.com o al +1 844-420-6883.",

  "action.edit": "Editar",
  "action.exportPdf": "Exportar PDF",
  "action.share": "Compartir enlace",
  "action.copy": "Copiar resumen",
  "action.done": "Ver tabla",
  "action.close": "Cerrar",
  "toast.copied": "Resumen copiado",
  "toast.linkCopied": "Enlace copiado",
  "toast.failed": "No se pudo copiar. Seleccione la barra de direcciones y cópiela.",

  "chip.stock": "Concentrado",
  "chip.direct": "Directo a la reserva",
  "chip.dosers3": "3 dosificadores",
  "chip.dosers2": "2 dosificadores",
  "chip.tankGal": "Tanques de {vol} gal",
  "chip.custom": "Personalizado {a} / {b} / {bl} lb/gal",
  "chip.caStock": "CaNO3 {rate} lb/gal",
  "chip.nearRipen": "Final Near Ripen",
  "chip.high": "EC de alta concentración",
  "chip.standard": "EC estándar",
  "chip.customEc": "EC personalizada",
  "chip.schedule.commercial": "Programa comercial",
  "chip.schedule.swell-flower": "Swell toda la floración",
  "chip.schedule.custom": "Recetas personalizadas",
  "chip.schedule.locked": "Swell fijo",
  "chip.phz": "PhosZyme",

  "unit.mL/gal": "mL/gal",
  "unit.injection %": "% de inyección",
  "unit.ratio": "proporción",
  "unit.mL/L": "mL/L",
  "unit.g/gal": "g/gal",
  "unit.g/L": "g/L",
  "unitCaption.mL/gal": "mL de concentrado por galón de agua de riego",
  "unitCaption.injection %": "tasa de inyección, % del caudal",
  "unitCaption.ratio": "proporción del inyector, concentrado a agua",
  "unitCaption.mL/L": "mL de concentrado por litro de agua de riego",
  "unitCaption.g/gal": "gramos de producto por galón de reserva",
  "unitCaption.g/L": "gramos de producto por litro de reserva",

  "phase.short.0": "Veg / Madres",
  "phase.short.1": "Sem 1–2",
  "phase.short.2": "Sem 3–5",
  "phase.short.3": "Sem 6–8/9",
  "phase.short.4": "Últimas 1–2 sem",
  "phase.long.0": "Veg / Madres",
  "phase.long.1": "Semana 1–2",
  "phase.long.2": "Semana 3–5",
  "phase.long.3": "Semana 6–8/9",
  "phase.long.4": "Últimas 1–2 sem",
  "sec.schedule": "Programa de alimentación",
  "chart.phase": "Fase",
  "chart.ec": "EC",
  "chart.recipe": "Receta",
  "chart.targetEc": "EC objetivo",
  "chart.dripperPh": "pH en gotero",
  "chart.ph": "pH {range}",
  "chart.notServed": "No se cubre",
  "chart.bars": "Las barras muestran el aporte de EC de cada parte.",
  "chart.subEc": "Las cifras pequeñas son la aportación de EC de cada parte por separado.",
  "chart.valuesAre": "Valores en {caption}.",
  "chart.disclaimer": "Estas tablas no son una prescripción, sino un ejemplo de los rangos generales y de la relación entre EC y recetas que pueden usarse. Cada instalación y metodología de cultivo requerirá ajustar los valores de EC. Vea \"Consideraciones de EC\".",
  "ph.title": "pH en gotero",
  "ph.body": "El rango de cada fase sigue su receta y su EC objetivo, según el modelo de fosfato de calcio. Suba el pH con pH Up solo hasta el tope del rango.",
  "ph.warm": "Las líneas que corren por encima de {c} °C ({f} °F) deben usar el extremo bajo del rango.",
  "twoDoser.veg": "Veg / Madres no se cubre con 2 dosificadores: un tanque combinado {combo} no puede entregar una receta Veg sin {bloom}. Alimente veg / madres con una mezcla aparte de {a} + {b}.",
  "twoDoser.rates": "Los dos tanques corren a tasas de inyección distintas. Ajuste cada dosificador a la tasa de su propia fila y confirme con la validación de EC/PPM.",
  "twoDoser.equal": "Con CaNO3 a 0.75 lb/gal y Swell al final, ambos dosificadores corren a la misma tasa.",
  "custom.mkpCool": "El MKP por encima de 1.33 lb/gal puede no disolverse por completo en agua fría. Mézclelo en agua a temperatura ambiente y confirme la EC de validación antes de usarlo.",

  "sec.tanks": "Tanques de concentrado",
  "tanks.each": "{vol} {unit} cada uno",
  "tanks.split": "Tanque 1 {a} {unit} · Tanque 2 {b} {unit}",
  "tank.n": "Tanque {n}",
  "tank.validates": "Valida a {ec} EC",
  "tank.validatesTotal": "El tanque valida a {ec} EC",
  "tank.phzAdds": "PhosZyme suma {ec} EC a la lectura de este tanque.",
  "tank.with": "con {items}",
  "tank.validation": "Valide cada tanque: {ml} mL de concentrado en {water} de agua RO deben dar su EC de validación.",
  "water.us": "5 gal",
  "water.metric": "20 L",

  "sec.mix": "Pasos de mezcla",
  "sec.notes.stock": "Notas para el concentrado",
  "sec.notes.direct": "Notas de directo a la reserva",
  "step.stock.1": "Comience con tanques de concentrado limpios marcados al volumen deseado.",
  "step.stock.2": "Agregue agua RO hasta el 50 % del volumen deseado; comience a agitar el tanque.",
  "step.stock.3": "Agregue el fertilizante durante 5 minutos mientras sigue agitando el tanque.",
  "step.stock.4": "Agregue agua RO hasta el volumen deseado; mezcle 10 minutos más.",
  "step.stock.5": "Valide y ajuste el tanque de concentrado según sea necesario (vea Validación).",
  "step.two.1": "Comience con dos tanques de concentrado limpios marcados al volumen deseado.",
  "step.two.2": "Agregue agua RO hasta el 50 % del volumen deseado en cada tanque; comience a agitar.",
  "step.two.3part.3": "Tanque 1: agregue Part A durante 5 minutos mientras agita. Tanque 2: agregue Part B, luego PhosZyme y luego Bloom durante 5 minutos mientras agita. Bloom es la adición más grande y la más lenta que se disuelve.",
  "step.two.3part.3.nophz": "Tanque 1: agregue Part A durante 5 minutos mientras agita. Tanque 2: agregue Part B y luego Bloom durante 5 minutos mientras agita. Bloom es la adición más grande y la más lenta que se disuelve.",
  "step.two.cplus.3": "Tanque 1: agregue nitrato de calcio durante 5 minutos mientras agita. Tanque 2: agregue Component Plus y deje que se disuelva por completo, luego PhosZyme y luego MKP, mientras agita (MKP se disuelve lento en agua fría).",
  "step.two.cplus.3.nophz": "Tanque 1: agregue nitrato de calcio durante 5 minutos mientras agita. Tanque 2: agregue Component Plus y deje que se disuelva por completo, luego MKP, mientras agita (MKP se disuelve lento en agua fría).",
  "step.two.4": "Agregue agua RO hasta el volumen deseado en cada tanque; mezcle 10 minutos más.",
  "step.two.5": "Valide y ajuste cada tanque de concentrado según sea necesario (vea Validación).",
  "step.two.6": "Ajuste cada dosificador a su propia tasa de inyección según la tabla; confirme la EC/PPM de la solución final.",
  "step.dtr.1": "Llene la reserva al 90 % del volumen final previsto; comience la agitación.",
  "step.dtr.2": "Si usa pH Down: agréguelo hasta el rango objetivo antes de agregar el fertilizante.",
  "step.dtr.add": "Agregue {product}; agite 3–5 minutos.",
  "step.dtr.addPhz": "Agregue {product} y PhosZyme; agite 3–5 minutos.",
  "step.dtr.6": "Mida EC/PPM y luego complete lentamente con agua hasta alcanzar su EC/PPM objetivo.",
  "step.dtr.7": "Si usa pH Up: agréguelo hasta el rango objetivo después de que EC/PPM esté en el objetivo.",
  "step.dtr.8": "Valide pH/EC y ajuste según sea necesario.",
  "note.stock.3part.1": "Mezcle cada parte en su propio tanque de concentrado individual; valide la EC del concentrado antes de usarlo y ajuste según sea necesario.",
  "note.stock.3part.2": "El Tanque 1 lleva solo Part A. El Tanque 2 lleva Part B y Bloom juntos: mezcle primero Part B y luego Bloom. Valide la EC de cada tanque de concentrado antes de usarlo y ajuste según sea necesario.",
  "note.ro": "Todas las tablas de alimentación suponen agua RO. Si su agua inicial tiene EC, inclúyala en la EC total.",
  "note.phz.3part": "Si usa PhosZyme, mézclelo en el tanque de concentrado de Part B, nunca con Part A.",
  "note.phz.3part.two": "Si usa PhosZyme, mézclelo en el Tanque 2 después de Part B y antes de Bloom, nunca con Part A.",
  "note.oxidizers.stock": "Evite mezclar oxidantes fuertes, especialmente peróxidos, en los tanques de concentrado.",
  "note.injectors": "Ajuste los inyectores a las tasas indicadas y confirme la EC/PPM de la solución final en el emisor.",
  "note.injectors.two": "Los dos tanques corren a tasas de inyección distintas. Ajuste cada dosificador a la tasa de su propia fila y confirme la EC/PPM de la solución final en el emisor.",
  "note.cplus.shelf": "Use los concentrados de C+ dentro de los 14 días posteriores a la mezcla. Guárdelos en recipientes opacos a temperatura ambiente, sin contacto con el suelo y lejos de la luz directa o artificial.",
  "note.cplus.separate": "Mantenga CaNO3, Component Plus y MKP en tanques de concentrado separados.",
  "note.cplus.separate.two": "Mantenga CaNO3 solo en el Tanque 1. En el Tanque 2, disuelva Component Plus por completo antes de agregar MKP.",
  "note.cplus.validate": "Prepare los concentrados con agua RO y valide cada tanque antes de usarlo.",
  "note.phz.cplus": "Agregue PhosZyme al tanque de Component Plus, nunca al tanque de CaNO3.",
  "note.phz.cplus.two": "Agregue PhosZyme después de Component Plus y antes de MKP en el Tanque 2, nunca al tanque de CaNO3.",
  "note.dtr.days": "Las reservas deben consumirse en 5–7 días.",
  "note.dtr.oxidizers.us": "Evite mezclar oxidantes fuertes, especialmente peróxidos, en las reservas. Si maneja una reserva estéril, use hipoclorito de calcio a unos {g} g por 100 gal para {ppm} ppm.",
  "note.dtr.oxidizers.metric": "Evite mezclar oxidantes fuertes, especialmente peróxidos, en las reservas. Si maneja una reserva estéril, use hipoclorito de calcio a unos {g} g por 100 gal ({gL} g por 100 L) para {ppm} ppm.",
  "note.dtr.phz.3part": "Si usa PhosZyme, agréguelo con Part B.",
  "note.dtr.phz.cplus": "Si usa PhosZyme, agréguelo con Component Plus, después de CaNO3 y antes de MKP.",

  "sec.validation": "Validación",
  "val.1": "Tome {ml} mL del tanque de concentrado.",
  "val.2": "Mezcle la muestra en {water} de agua RO.",
  "val.3": "Mida la EC y compárela con la columna EC valid.",
  "val.4": "Si la lectura no coincide, ajuste el tanque y vuelva a validar antes de usarlo.",
  "val.phz": "PhosZyme en el tanque de {carrier} eleva la EC de validación de ese tanque.",
  "stock.title": "Dosis de concentrado {label}",
  "stock.tank": "Tanque",
  "stock.part": "Parte",
  "stock.validEc": "EC valid.",
  "stock.tank2Total": "Total Tanque 2",

  "sec.supps": "Suplementos",
  "supps.hint": "Agregue pH Up, BioFlo o Triologic a esta lista en Editar.",
  "supp.si.name": "Front Row Si",
  "supp.si.rate": "{rate}",
  "supp.si.note": "Aspersión foliar, una vez por semana, de Veg a la semana 3 de floración.",
  "supp.phup.name": "Front Row pH Up",
  "supp.phup.rate": "máx. {max} {unit}",
  "supp.phup.note": "Suba el pH al rango recomendado en la tabla. Agréguelo al final, en pasos de {inc} {unit}; espere {wait} minutos antes de volver a medir. Deténgase en {stop} {unit} en floración de alta concentración.",
  "supp.bioflo.name": "BioFlo",
  "supp.bioflo.rate": "{heavy} profunda · {maint} mantenimiento",
  "supp.bioflo.note": "Limpiador de biopelícula para líneas. Limpieza profunda: remojo de {soak} horas. Mantenimiento cada {weeks} semanas.",
  "supp.tri.name": "Triologic",
  "supp.tri.rate": "{weekly} semanal",
  "supp.tri.note": "Inoculante microbiano que amplifica la colonización micorrízica. Riego manual semanal; hasta {max} (por ejemplo, en el trasplante).",
  "supp.additive": "Aditivo",
  "supp.rate": "Dosis",
  "supp.notes": "Notas",
  "supp.title": "Dosis de uso de aditivos",

  "ec.considerations": "Consideraciones de EC",
  "ec.considerationsBody": "Dada la variación en infraestructura, métodos de cultivo y cultivares, es imposible dar una prescripción de EC específica que aplique a todos los casos. La mayoría de las instalaciones alimentan a 2.0–3.0 EC con Front Row Ag, y nuestras tablas \"Estándar\" y \"Alta concentración\" reflejan estrategias de alimentación eficaces en ese rango.",
  "ec.higherLower": "EC más alta vs. EC más baja",
  "ec.higher": "EC más alta",
  "ec.lower": "EC más baja",
  "hl.0.h": "Macetas más pequeñas", "hl.0.l": "Macetas más grandes",
  "hl.1.h": "Riego frecuente", "hl.1.l": "Riego poco frecuente",
  "hl.2.h": "Drenaje constante", "hl.2.l": "Menos drenaje",
  "hl.3.h": "Monitoreo del sustrato", "hl.3.l": "Sin monitoreo del sustrato",
  "hl.4.h": "PPFD más alto", "hl.4.l": "PPFD más bajo",
  "hl.5.h": "Variedades de alta demanda", "hl.5.l": "Variedades de baja demanda",
  "hl.6.h": "CO2 más alto", "hl.6.l": "CO2 más bajo",
  "hl.7.h": "Control ambiental estricto", "hl.7.l": "Menor control ambiental",
  "ec.contribution": "Aporte de EC",
  "ec.perUnit": "EC por {unit}",

  "print.kicker": "{line} · {application}",
  "print.feedChart": "Tabla de alimentación",
  "print.mixing": "Instrucciones de mezcla",
  "print.preparedFor": "Preparado para",
  "print.notes": "Notas",
  "print.page": "Página {n} de {total}",
  "print.artTitle.stock": "Cómo preparar el concentrado",
  "print.artTitle.direct": "Mezcla paso a paso",
  "print.artTitle.line": "Cómo se instala la línea de dos dosificadores",
  "print.tankKey": "Qué contiene cada tanque",
  "print.phUpDoser": "Tercer dosificador opcional: pH Up",
  "print.qr": "Más información sobre la tabla de alimentación",
  "art.stock.1": "Llene al {pct} % con agua RO; comience a agitar",
  "art.stock.2": "Agregue el producto durante {min} min",
  "art.stock.3": "Complete; mezcle {min} min más",
  "art.stock.4": "Valide: {ml} mL en {water} de RO",
  "art.dtr.1": "Llene al {pct} %; comience a agitar",
  "art.dtr.2": "Agregue cada parte; {min} min entre cada una",
  "art.dtr.3": "Complete hasta la EC objetivo",
  "art.dtr.4": "pH Up al final; mida el pH en el gotero",
  "lines.3part": "3-Part",
  "lines.cplus": "Component Plus",
  "summary.title": "Tabla de alimentación Front Row Ag",
  "summary.facility": "Instalación: {name}",
  "summary.link": "Enlace de la tabla: {url}",

  "edit.title": "Personalice su tabla de alimentación",
  "field.facility": "Nombre de la instalación",
  "field.facilityHelp": "Opcional. Aparece en la tabla impresa.",
  "field.facilityPlaceholder": "Nombre de la instalación",
  "field.application": "Aplicación",
  "opt.stock": "Concentrado",
  "opt.direct": "Directo a la reserva",
  "help.more": "¿Qué significan?",
  "help.application.stock": "El concentrado es la configuración comercial estándar. El fertilizante se premezcla en tanques para concentrados y luego se inyecta en la línea de riego con equipos de dosificadores (inyectores). La tabla muestra cuánto producto va en cada tanque de concentrado y la tasa de inyección de cada dosificador.",
  "help.application.direct": "Directo a la reserva es para instalaciones que mezclan los nutrientes directamente en una reserva o tanque de lote a la concentración de uso, sin tanques de concentrado ni inyectores. La tabla muestra cuánto producto agregar por galón (o por litro) de solución final.",
  "field.dosers": "Dosificadores",
  "opt.dosers3": "3 dosificadores",
  "opt.dosers2": "2 dosificadores",
  "help.dosers.3part.3": "3 dosificadores: Part A, Part B y Bloom tienen cada uno su propio tanque de concentrado e inyector. Es la configuración estándar y permite cambiar la receta en cada fase.",
  "help.dosers.3part.2": "2 dosificadores: Part A en el Tanque 1, y Part B + Bloom combinados en el Tanque 2. Un tanque combinado fija la proporción Part B–Bloom, así que todas las fases de floración corren la receta Swell. El Tanque 1 es el mismo tanque de Part A de la mezcla 3-2-2. Los dos tanques corren a tasas de inyección distintas.",
  "help.dosers.cplus.3": "3 dosificadores: CaNO3, C+ y MKP tienen cada uno su propio inyector, mezclados a 1 lb por galón (1-1-1). Las tasas de inyección difieren entre tanques porque cada producto aporta una parte distinta de la EC total.",
  "help.dosers.cplus.2": "2 dosificadores: CaNO3 solo en el Tanque 1, y C+ + MKP combinados en el Tanque 2 a 0.75 + 1.00 lb/gal. El calcio nunca puede compartir tanque con fosfato ni sulfato, así que CaNO3 siempre va solo. El tanque combinado fija la proporción C+–MKP, así que la floración corre Swell con una fase final Near Ripen opcional.",
  "field.method": "Método de mezcla",
  "opt.custom": "Personalizado",
  "help.method.3-2-2": "3-2-2 es el método estándar. Tres bolsas de 25 lb de Part A van en un tanque de concentrado de 50 gal (75 lb a 1.5 lb/gal). Part B y Bloom llevan dos bolsas de 25 lb cada uno en 50 gal (50 lb a 1 lb/gal). Las tasas de inyección salen iguales para las tres partes en la receta Stack, e iguales para Part A y Part B en Veg; las demás recetas corren cada parte a su propia tasa.",
  "help.method.1-1-1": "1-1-1 mezcla todo a 1 lb por galón: 50 lb de cada parte en tanques de concentrado de 50 gal. Es una concentración menor que 3-2-2. Las tasas de inyección difieren entre partes porque cada una aporta una parte distinta de la EC total.",
  "help.method.4-3-3": "4-3-3 mezcla Part A a 1.87 lb/gal en 53.5 gal, y Part B y Bloom a 1.25 lb/gal en 60 gal.",
  "help.method.custom": "Personalizado define las libras cargadas en cada tanque y el tamaño del tanque. Las tasas y las EC de validación se recalculan a partir de estos valores.",
  "help.method.cplus": "El concentrado de Component Plus se mezcla a 1 lb por galón en cada uno de los tres tanques (1-1-1). Las tasas de inyección difieren entre tanques porque cada producto aporta una parte distinta de la EC total.",
  "field.tankSize": "Tamaño del tanque de concentrado",
  "field.tankUnit": "gal por tanque de concentrado",
  "help.tank.3part": "Se aplica a ambos tanques de concentrado. El valor predeterminado de 50 gal cabe en un barril estándar de 55 gal. El Tanque 2 es el más diluido y corre a una tasa de inyección mayor, así que se vacía 1.7 veces más rápido que el Tanque 1; use un tanque más grande o planifique los rellenos.",
  "help.tank.cplus": "Se aplica a cada tanque de concentrado. Elija el volumen que vaya a consumir en 14 días.",
  "help.tank.custom": "Se aplica a los tres tanques.",
  "help.tank.min": "Mínimo {min} gal.",
  "field.customLbs": "Fertilizante por tanque",
  "field.lbCharged": "lb cargadas",
  "help.customLbs": "Solo uso interno. lb/gal, tasas de inyección y EC de validación se recalculan a partir de estos valores. Límite de {a} / {b} / {bl} lb/gal ({names}). Valide la EC del concentrado antes de usarlo.",
  "field.caStock": "Concentración de CaNO3",
  "opt.ca.0.75": "0.75 lb/gal · Swell a tasa igual",
  "opt.ca.1": "1.00 lb/gal · bolsa completa",
  "help.caStock": "El Tanque 2 se mantiene en 0.75 lb/gal de Component Plus + 1.00 lb/gal de MKP. La opción de 1.00 lb/gal de CaNO3 requiere tasas de inyección separadas.",
  "field.finalPhase": "Fase final",
  "opt.fp.swell": "Swell",
  "opt.fp.near-ripen": "Near Ripen",
  "help.finalPhase": "Near Ripen mantiene el calcio en la proporción de Ripen (31.5 % de la EC total) y asigna el 68.5 % restante al tanque fijo de C+ + MKP. Es una aproximación de dos tanques, no la receta Ripen de tres productos.",
  "field.units": "Unidades de salida",
  "field.ec": "EC objetivo",
  "opt.high": "Alta concentración",
  "opt.standard": "Estándar",
  "help.ec": "Al editar la EC de una fase se cambia a Personalizada.",
  "field.schedule": "Programa de recetas",
  "opt.schedule.commercial": "Comercial",
  "opt.schedule.swell-flower": "Swell toda la floración",
  "opt.schedule.custom": "Personalizado",
  "help.schedule.commercial": "Comercial (Stack → Swell), la tabla predeterminada, es el programa de producción simplificado: Veg / Madres con Veg, la receta Stack al inicio de floración (sem 1–2), luego Swell el resto y Ripen al final. Swell baja en escalones a mitad de floración: semanas 3–5 a la EC de Swell más alta (2.7 Alta / 2.2 Estándar), semanas 6–8/9 a la más baja (2.4 Alta / 2.0 Estándar).",
  "help.schedule.swell-flower": "Swell toda la floración mantiene Veg / Madres en la receta Veg y luego corre Swell durante toda la floración: el programa de floración de una sola receta más sencillo. Como el LED de alta intensidad, la iluminación bajo el dosel y el riego de precisión han subido la EC promedio, Swell da mejores resultados a esas EC más altas.",
  "help.schedule.custom": "Personalizado aparece cuando cambia la receta de una fase abajo.",
  "help.schedule.locked.3part": "El modo de 2 dosificadores fija todas las fases en la receta Swell: el tanque combinado se pesa a la proporción Part B–Bloom de Swell y no puede redividirse por fase.",
  "help.schedule.locked.cplus": "El modo de 2 dosificadores corre el tanque fijo de C+ + MKP en Swell durante la floración. La fase final puede mantener Swell o bajar el calcio a Near Ripen.",
  "field.recipes": "Receta por fase",
  "field.supps": "Suplementos",
  "opt.phz": "PhosZyme",
  "opt.phup": "pH Up",
  "opt.bioflo": "BioFlo",
  "opt.tri": "Triologic",
  "help.supps": "PhosZyme cambia la tabla. pH Up, BioFlo y Triologic agregan sus dosis a la lista de suplementos y al resumen; la tabla impresa incluye todos los aditivos.",
  "help.phz.3part": "PhosZyme va en su tanque de concentrado portador al 10 % del peso del portador (5 lb por tanque de 50 lb), lo que mantiene la dosis aplicada en o cerca de 0.4 g/gal. El portador es Part B (o el tanque combinado B + Bloom con 2 dosificadores). PhosZyme no es compatible con calcio, así que nunca va en un tanque con Part A. La tabla reduce un poco todas las dosis para que la EC total, incluida la de PhosZyme, llegue a su objetivo.",
  "help.phz.cplus": "PhosZyme va en el tanque de Component Plus al 10 % del peso de C+ (5 lb por tanque de 50 lb), lo que mantiene la dosis aplicada en o cerca de 0.4 g/gal. Con 2 dosificadores, el portador es el tanque combinado C+ + MKP. PhosZyme no es compatible con calcio, así que nunca va en un tanque con CaNO3. La tabla reduce un poco todas las dosis para que la EC total, incluida la de PhosZyme, llegue a su objetivo.",
  "help.phup": "pH Up sube el pH al rango de gotero que muestra la tabla para cada fase. Agréguelo al final, después de todos los nutrientes, en pasos de {inc} {unit}, y espere {wait} minutos antes de volver a medir. Máximo {max} {unit} en total; la floración de alta concentración debe detenerse en {stop} {unit}.",
  "help.bioflo": "BioFlo es un limpiador bioenzimático que elimina la biopelícula de las líneas de riego. No es un aditivo de alimentación; úselo como remojo periódico entre ciclos o durante ellos.",
  "help.tri": "Triologic es un inoculante microbiano con bacterias auxiliares de la micorrización. Amplifica la colonización micorrízica como riego manual semanal junto con un inoculante micorrízico aparte.",
  "help.si": "Front Row Si es una aspersión foliar; su dosis siempre aparece con los suplementos.",

  "gate.title": "Front Row Ag · Calculadora Component Plus",
  "gate.intro": "Esta calculadora es parte del programa comercial Component Plus de Front Row Ag y está disponible para los clientes participantes. Ingrese el código de acceso que le dio su representante de Front Row Ag.",
  "gate.placeholder": "Código de acceso",
  "gate.unlock": "Desbloquear calculadora",
  "gate.error": "Ese código no coincide. Consulte con su representante de Front Row Ag.",
  "gate.team.title": "Front Row Ag · Tabla del equipo",
  "gate.team.intro": "El modo de equipo es para el equipo de Front Row Ag. Ingrese el código del equipo de la página Team Tools de Notion.",
  "gate.team.error": "Ese código no coincide. El código del equipo está en la página Team Tools de Notion.",
};

export const STRINGS = { en, es };
